Add 'CLSAG' Moneropedia entry
monero-project/monero-site pull request #1181
Opened 2020-09-08 11:49 UTC by erciccione

Closes #1141

2020-09-08 12:48 UTC, SarangNoether requested changes

2020-09-08 12:48 UTC, SarangNoether commented on _i18n/en/resources/moneropedia/clsag.md
> +CLSAG (Concise Linkable Ring Signatures) is the new way Monero builds @ring-signatures, which replaces MLSAG (multilayered Linkable Spontaneous Anonymous Group Signature). CLSAG went live and mandato
CLSAG (Concise Linkable Spontaneous Anonymous Group) signatures are...

2020-11-23 13:18 UTC, erciccione commented
Rebased and adapted to https://github.com/monero-project/monero-site/pull/1198 (`clsag` only to the English yaml file)

2020-11-27 20:51 UTC, SamsungGalaxyPlayer requested changes
Looks awesome, though can we also include the CLSAG logo at the bottom from https://github.com/monero-project/monero-site/blob/master/blog/assets/clsag/clsag.svg

2020-11-28 13:15 UTC, erciccione commented
Would be nice to have some colour in the page, but adding an image would be inconsistent with the other entries, don't know if the change worths it.

2020-11-30 15:20 UTC, SamsungGalaxyPlayer commented
Is there a significant reason not to? If a diagram or something would be useful in another Moneropedia entry, I would support its inclusion.

2020-12-02 10:17 UTC, erciccione commented
@SamsungGalaxyPlayer I did a couple of tests. If we want the image to be centered, we need to add an html block. I would avoid that because it would complicate things when will be time to feed these documents to weblate. Would be different for a diagram, since it wouldn't need to be centered IMO. I would prefer to avoid this logo since it's more a complication than anything. We also link from this page to the blog post announcing CLSAG, which have the image right at the top.

2020-12-03 23:16 UTC, SamsungGalaxyPlayer approved these changes

2020-12-14 18:05 UTC, merged