Add 'LyraHosting' to the list of merchants
monero-project/monero-site pull request #1212
Opened 2020-09-26 00:21 UTC by l33d4n

Closes #1194

2020-09-26 06:55 UTC, erciccione requested changes

2020-09-26 06:55 UTC, erciccione commented on _data/merchants.yml
> +    - name: LyraHosting - LyraHosting is a solid offshore hosting company
```suggestion
    - name: LyraHosting - Offshore hosting company
```

2020-09-26 16:26 UTC, erciccione approved these changes

2020-10-08 15:25 UTC, merged

2020-10-08 18:10 UTC, LyraHosting commented
Hello guys,
Have you approved this?

2020-10-09 02:46 UTC, l33d4n commented
Yes. **erciccione** approved it and **luigi1111** merged it.