Moneropedia entries into Norwegian (A–B)
monero-project/monero-site pull request #1266
Opened 2020-10-21 16:55 UTC by MindWallet

Moneropedia entries into Norwegian (A–B)

2020-10-21 16:58 UTC, MindWallet commented
I tried to edit my last pull request, but it seems a new one was made. Sorry about that. I will try to make the next one in my terminal, so please bear with me as I am a novice when it comes to this stuff.

2020-10-22 09:15 UTC, erciccione requested changes
The review started in #1259. Beside that looks good.

2020-10-22 09:15 UTC, erciccione commented on _i18n/nb-no/resources/moneropedia/address-book.md
> +For spesifikasjonsdetaljer og mer, kan du besøke [Adressebok og navnespesifikasjon](https://geti2p.net/en/docs/naming)
As i mentioned in the other PR, this entry has been recently removed (#1219) and should  be removed from this PR as well.

2020-11-20 10:23 UTC, erciccione commented on _i18n/nb-no/resources/moneropedia/address-book.md
> +For spesifikasjonsdetaljer og mer, kan du besøke [Adressebok og navnespesifikasjon](https://geti2p.net/en/docs/naming)
Fixed.

2020-11-24 09:29 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/account.md
> +Kontoen din inneholder alle Monero-transaksjonene du har sendt og mottatt. Kontobalansen din er summen av alle Moneroene du har mottatt, fratrukket Moneroene du har mottatt. Når du bruker Monero, leg
Kontobalanse -> Kontosaldo

2020-11-24 09:34 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/account.md
> +Kontoen din er basert på to nøkler – en forbruksnøkkel og en visningsnøkkel. Forbruksnøkkelen er spesiell i og med at det er den eneste nøkkelen som trengs for å bruke Monero-midlene dine, mens visni
Not a mistake, but "bokføringsøyemed" sounds better.

2020-11-24 09:40 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/address.md
> +summary: "enten et alias, som for eksempel donate.getmonero.org, eller et sett med 95 tegn som starter med en 4"
Perhaps change "started med en" with "begynner med"

2020-11-24 09:42 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/airgap.md
> +«En luftvegg, ‘air gap’ eller ‘air gapping’ er et sikkerhetstiltak som brukes på ett eller flere PC-er for å sikre at et sikkert PC-nettverk er fysisk isolert fra usikrede nettverk, som for eksempel
ett -> én

2020-11-24 09:47 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/block.md
> +Falske eller dårlige blokker kan generelt ikke opprettes, i og med at noder som mottat blokker alltid verifiserer transaksjonene de inneholder  mot et sett med konsensusregler som alle noder føyer se
mottatt -> mottar

Also, I think there is an extra space after "inneholder"

2020-11-24 10:11 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/bulletproofs.md
> +I 2017 krev en [krypto-gruppe på Stanford](https://crypto.stanford.edu/bulletproofs/) en [vitenskapelig artikkel](https://eprint.iacr.org/2017/1066.pdf) der de presenterte en ny type rekkeviddebevis,
typo: -> skrev*

2020-11-24 10:11 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/bulletproofs.md
> +I motsetning til Borromean- eller Schnorr-signaturer, er bulletproofs veldig effektive som rekkeviddebevis. Å bevise en stort datamengde genererer kun et lite bevis, og størrelsen på disse bevisene v
Typo: stort -> stor

2020-11-24 10:47 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/bulletproofs.md
> +I og med at bulletproofs var veldig nytt og den opprinnelige implementeringen som ble gjort av gruppen – til tross for at den ble gjort grundig – trengte den en omskriving som var fokusert på vårt sp
Remove "den" + typo in "omskriving"

2020-12-10 11:26 UTC, erciccione reviewed
Looks good except for one minor detail.

2020-12-10 11:26 UTC, erciccione commented on _i18n/nb-no/resources/moneropedia/address.md
> +Hvis du vil få din egen OpenAlias-adresse, finnes informasjon om dette på [OpenAlias-siden](/the-monero-project/).
Please adapt to #1309

```suggestion
Hvis du vil få din egen OpenAlias-adresse, finnes informasjon om dette på [OpenAlias-siden](https://openalias.org/).
```

2020-12-10 11:34 UTC, erciccione approved these changes
Needs to be squashed.

2020-12-10 11:51 UTC, erciccione requested changes
'@' tags need to be reintroduced.

2020-12-10 16:50 UTC, erciccione approved these changes

2020-12-14 18:09 UTC, merged