Norwegian Moneropedia entries (C-D)
monero-project/monero-site pull request #1281
Opened 2020-10-31 16:04 UTC by MindWallet

2020-11-01 12:00 UTC, erciccione requested changes

2020-11-01 12:00 UTC, erciccione commented on _i18n/nb-no/resources/moneropedia/account.md
> +terms: ["konto", "kontoer", "lommebok", "lommebøker"]
The english term must be included. Same for all other entries

2020-11-01 12:15 UTC, MindWallet commented on _i18n/nb-no/resources/moneropedia/address-book.md
> +For spesifikasjonsdetaljer og mer, kan du besøke [Adressebok og navnespesifikasjon](https://geti2p.net/en/docs/naming)
Yeah, I am aware. Not quite sure how it reappeared. I also had added the English entry. I will try to fix it when I am back home. Somehow an old version seems to be there.

2020-11-11 17:11 UTC, closed without merging

2020-11-11 17:12 UTC, erciccione commented
Continue in #1302