9 Norwegian Moneropedia entries (C–D)
monero-project/monero-site pull request #1302
Opened 2020-11-11 17:09 UTC by MindWallet

2020-11-24 10:50 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/canonically-unique-host.md
> +terms: ["Kanonisk-unik-vert"]
Add English term

2020-11-24 10:52 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/canonically-unique-host.md
> +- Monero bruker primært en kanonisk-unik-vert-resolusjon, mens I2P bare bruker lokal-unik-vert-resolusjon.
Perhaps add "en" after "bruker" in the last part for consistency

2020-11-24 10:52 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/change.md
> +Lommeboken i Monero-programvaren lager veksel automatisk, men når du sender en transaksjon, tar du en inndata som du kontrollerer og forteller Monero-nettverket hva som skal gjøre med det. Inndataen
typo: gjøres*

2020-11-24 10:57 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/clearnet.md
> +Fordi en tradisjonell [VPN](https://en.wikipedia.org/wiki/VPN) ikke kan redde deg fra clearnet (i og med at du fremdeles bruker *clearnet* (selvom du er mer sikret enn uten en VPN)), bør du bruke et
Typo: selv om*

2020-11-24 10:59 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/clearnet.md
> +Her er et nøyaktig, [interaktivt diagram](https://www.eff.org/pages/tor-and-https) gitt av [EFF](https://www.eff.org/) som beskriver *clearnet* i sammenheng med **Tor**. Konseptet gjelder også (i en
Konseptet gjelder også (i en viss grad) for*

2020-11-24 11:01 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/cryptocurrency.md
> +terms: ["cryptocurrency", "cryptocurrencies", "altcoin", "altcoins","kryptovaluta", "kryptovalutaer", "altcoin", "altcoins"]
spacing error

2020-11-24 11:06 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/cryptocurrency.md
> +Monero er én av mange kryptovalutaer som er tilgjengelig. Andre eksempler er Bitcoin, Litecoin, Dogecoin, Dash, Zcash, osv, men nesten alle andre kryptovaluta mangler funksjoner som gjør dem til ekte
.. kan kalles for et*

2020-11-24 11:11 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/denominations.md
> +terms: ["denominations", "subunits", "valører", "underenheter", "tacoshi", "piconero", "nanonero", "micronero", "millinero", "centinero", "decinero","decanero","hectonero","kilonero","meganero","giga
fix spacing

2020-11-24 11:12 UTC, StineeH commented on _i18n/nb-no/resources/moneropedia/denominations.md
> +| kilonero   | 10^3     | 1 000             |
1 000 -> 1000*

2020-12-10 11:29 UTC, erciccione approved these changes
Needs to be squashed.

2020-12-10 11:51 UTC, erciccione requested changes
'@' tags need to be reintroduced.

2020-12-10 16:57 UTC, erciccione approved these changes
There are some tags that point to entries that got removed, but doesn't matter, i will fix them in bulk later on.

2020-12-14 18:10 UTC, merged