Add Italian subtitles for the what-is-monero video in home
monero-project/monero-site pull request #1386
Opened 2020-12-24 09:25 UTC by staff91

2020-12-26 11:42 UTC, erciccione requested changes

2020-12-26 11:42 UTC, erciccione commented on index.html
> +                            <track label="English" kind="subtitles" srclang="en" src="/media/subtitles/en/monero-promo.vtt" default>
This will create conflicts and differs from #1373. Would be better to base your PR on that one.

2020-12-26 12:40 UTC, erciccione reviewed
Review of the Italian translation of the subtitles

2020-12-26 12:40 UTC, erciccione commented on media/subtitles/it/monero-promo.vtt
> +esiste un luogo sicuro dove condurre transazioni private. Beh, non ne esisteva uno fino ad ora. Ed ecco a voi Monero.
```suggestion
esiste un luogo sicuro dove condurre transazioni private. Beh, non ne esisteva uno fino ad ora. Ecco a voi Monero.
```

2020-12-26 12:40 UTC, erciccione commented on media/subtitles/it/monero-promo.vtt
> +Monero è una valuta sicura, privata, non rintracciabile. Con Monero sei tu la tua banca.
```suggestion
Monero è una valuta sicura, privata, non tracciabile. Con Monero sei tu la tua banca.
```

2020-12-26 12:40 UTC, erciccione commented on media/subtitles/it/monero-promo.vtt
> +e ai vicini ficcanaso o ai truffatori. Monero può anche essere selettivamente trasparente e puoi scegliere
```suggestion
possono tenere segreti i loro fornitori,
e individui possono sfuggire a governi repressivi

00:00:38.160 --> 00:00:44.160
e a vicini ficcanaso o ai truffatori. Monero può anche essere selettivamente trasparente e puoi scegliere
```

2020-12-26 12:40 UTC, erciccione commented on media/subtitles/it/monero-promo.vtt
> +chi vuoi che veda le transazioni. Monero è scalabile dinamicamente, il che lo rende molto diverso
```suggestion
chi vuoi che veda le transazioni. Monero scala dinamicamente, il che lo rende molto diverso
```

Not sure about this one, but "e' scalabile" doesn't sound right.

2020-12-26 12:40 UTC, erciccione commented on media/subtitles/it/monero-promo.vtt
> +da un Bitcoin. Inoltre, la ricompensa del blocco non scenderà mai al di sotto di 0,3 XMR e l'inflazione nominale
```suggestion
da Bitcoin. Inoltre, la ricompensa di blocco non scenderà mai al di sotto di 0,3 XMR e l'inflazione nominale
```

See the [terminology guide for Italian](https://github.com/monero-ecosystem/monero-translations/blob/master/terminology-guides/italian-terminology.md)

2020-12-26 12:40 UTC, erciccione commented on media/subtitles/it/monero-promo.vtt
> +di 30 collaboratori. Riprendi il controllo delle
```suggestion
di 30 sviluppatori. Riprendi il controllo delle
```

2020-12-29 09:29 UTC, staff91 commented
@erciccione Thanks for review!

2021-01-15 09:40 UTC, erciccione commented
@staff91 please implement the suggested changes and rebase :)

2021-01-25 16:40 UTC, erciccione commented
ping @staff91

2021-02-04 10:21 UTC, erciccione commented
This PR is abandoned. Recovered in #1450.

2021-02-04 10:21 UTC, closed without merging