Removed Bittrex
monero-project/monero-site pull request #1400
Opened 2021-01-02 21:10 UTC by Cactii1

Removed Bittrex Exchange (Monero de-listing announcement)

2021-01-02 21:19 UTC, selsta approved these changes

2021-01-03 10:05 UTC, erciccione requested changes

2021-01-03 10:05 UTC, erciccione commented on _data/merchants.yml
> -      url: https://sideshift.ai
These shouldn't be here. Seems like you pulled the commit from #1401

2021-01-15 09:37 UTC, erciccione commented
ping @Cactii1

2021-01-25 16:39 UTC, erciccione commented
Superseded by #1435

2021-01-25 16:39 UTC, closed without merging