Added FAQ "How big is the Monero blockchain?"
monero-project/monero-site pull request #1442
Opened 2021-01-28 17:29 UTC by tonyern

I added a new FAQ under the "Node and Wallet" section. I have the question and answer in English and Spanish.

2021-01-29 08:49 UTC, erciccione requested changes
I proposed some fixes.

2021-01-29 08:49 UTC, erciccione commented on _i18n/en.yml
> +  ablocksize: "The Monero @blockchain is always growing so there is no fixed size. As of 2021, the blockchain is around 95-100GB. "
Better add the size of a pruned blockchain as well.

2021-01-29 08:49 UTC, erciccione commented on _i18n/es.yml
> +  qblocksize: ¿Qué tan grande es la cadena de bloques Monero?
Translations must be submitted to weblate: translate.getmonero.org

Please revert all changes to this file.

2021-01-30 09:01 UTC, erciccione commented on _i18n/en.yml
> +  ablocksize: "The Monero @blockchain is always growing so there is no fixed size. As of 2021, the full-node blockchain is around 95-100GB. Pruned-node blockchain is 30GB. Check out Moneropedia entry
```suggestion
  ablocksize: "The Monero @blockchain is always growing so there is no fixed size. As of 2021, the full blockchain is around 95-100GB. A pruned blockchain is about 30GB. Check out Moneropedia entry @pruning to learn the difference between full-node and pruned-node blockchains."
```

2021-01-31 09:21 UTC, erciccione approved these changes
Looks good now. Thanks :)

Closes #1371

2021-02-03 16:00 UTC, tonyern commented
What happens after approval of the pull request? Do I have to do anything else?

2021-02-04 01:55 UTC, rehrar approved these changes

2021-02-04 01:55 UTC, rehrar commented
The only comment I'd make here is "as of 2021" since late 2021 the blockchain will be quite a different size. But it's not super important atm.

2021-02-05 18:42 UTC, merged