Add video "Community & Key Aspects" to FAQ
monero-project/monero-site pull request #1476
Opened 2021-02-21 22:35 UTC by wirrickelliot

Closes #1188

2021-02-22 09:25 UTC, erciccione requested changes
The video is from 2018, it's heavily obsolete, doesn't really make sense to add it in the current state. It mentions Kovri right at the beginning and again later in the video, saying that it masks IP addresses; the data shown is from 2018 and 2 of the 3 communication channels suggested in the video don't exist anymore (slack and MatterMost). At the very end, it goes into details in describing the FFS, which has been replaced years ago by the CCS.

Too bad, because this video has some interesting info for the viewer, but needs to be heavily updated.

2021-02-22 13:12 UTC, wirrickelliot commented
That's my mistake. I figured since the issue was opened only a few months ago that it was still something needing to be addressed.
If I remove the video, would it still be worth merging simply to unify the hyperlink text and add the i18n key for Ring CT?

2021-02-24 08:35 UTC, erciccione commented
I was under the impression that the "community" video was going to be updated. I asked about it on #monero-community and got no answer, so i'm assuming there are no plans to update it. In this situation doesn't make sense to add it.

> would it still be worth merging simply to unify the hyperlink text and add the i18n key for Ring CT?

Sure, but please squash the commits into one and change title and description of the PR.

2021-02-25 08:11 UTC, erciccione approved these changes

2021-03-15 21:31 UTC, merged