Gettextize importing_blockchain.md, ledger-wallet-cli.md and mine-to-pool.md
monero-project/monero-site pull request #1530
Opened 2021-03-26 10:40 UTC by erciccione

Second batch of gettextized user guides (first batch is #1527):

- importing_blockchain.md
- ledger-wallet-cli.md
- mine-to-pool.md

In some case i had to touch the markdown files to fix a problem of mismatching strings (same string, same translation, but different bullet point. That caused po4a to not recognize the string). These files will need some minor tweaks (remove `-` from headers), but will be easier and faster to do it after the gettextization.

Part of #1270

2021-03-31 01:59 UTC, wirrickelliot requested changes

2021-03-31 07:55 UTC, erciccione commented on _i18n/nb-no/resources/user-guides/weblate/mine-to-pool.po
> +msgstr ""
All resolved, but i'm not sure about this one. What issues is it causing?

2021-03-31 10:16 UTC, wirrickelliot commented on _i18n/nb-no/resources/user-guides/weblate/mine-to-pool.po
> +msgstr ""
https://github.com/monero-project/monero-site/blob/f5e769bbfa079676b63eced9c828ba166093c32e/_i18n/en/resources/user-guides/weblate/mine-to-pool.pot#L364-L378

https://github.com/monero-project/monero-site/blob/f5e769bbfa079676b63eced9c828ba166093c32e/_i18n/nb-no/resources/user-guides/weblate/mine-to-pool.po#L451-L510

2021-04-01 07:27 UTC, erciccione commented on _i18n/nb-no/resources/user-guides/weblate/mine-to-pool.po
> +msgstr ""
Fixed. Thanks :)

2021-04-02 00:27 UTC, wirrickelliot approved these changes

2021-04-06 16:26 UTC, merged