Gettextize Offline_Backup.md, prove-payment.md and remote_node_gui.md
monero-project/monero-site pull request #1535
Opened 2021-03-28 09:32 UTC by erciccione

fourth batch of gettextized user guides (third batch: #1531)

Gettextized

- Offline_Backup.md
- prove-payment.md
- remote_node_gui.md

Part of #1270

2021-04-02 01:10 UTC, wirrickelliot requested changes
`_i18n/zh-tw/resources/user-guides/weblate/prove-payment.po` is missing.

2021-04-02 01:10 UTC, wirrickelliot commented on _i18n/tr/resources/user-guides/weblate/prove-payment.po
> +msgstr ""
Ditto

2021-04-02 01:10 UTC, wirrickelliot commented on _i18n/zh-cn/resources/user-guides/weblate/prove-payment.po
> +msgstr ""
Ditto

2021-05-06 06:55 UTC, erciccione commented
All fixed.

2021-05-16 03:27 UTC, wirrickelliot approved these changes

2021-05-22 02:35 UTC, merged