blog: fix minor issues
monero-project/monero-site pull request #1575
Opened 2021-04-14 14:05 UTC by alreadyburnt

![screen](https://user-images.githubusercontent.com/81592644/114722965-8af66680-9d3a-11eb-89f1-a37814c2afaf.jpg)

2021-04-19 16:02 UTC, selsta approved these changes
nice :)

2021-04-24 07:15 UTC, erciccione requested changes

2021-04-24 07:15 UTC, erciccione commented on blog/index.html
> +  <a href="#" class="arrow-up" aria-label="{% t accessibility.arrowup %}" title="{% t accessibility.gotop %}"><i></i></a>
The arrow is not showing up correctly

2021-05-28 08:12 UTC, erciccione commented
ping @alreadyburnt

2021-06-15 09:30 UTC, erciccione commented
ping.

2021-06-26 11:21 UTC, erciccione commented
PR recovered with #1689

2021-06-26 11:21 UTC, closed without merging