Initial draft of "This Year In Monero - 2021"
monero-project/monero-site pull request #1583
Opened 2021-04-19 17:43 UTC by sethsimmons

This is my first post here, but I think it should be pretty much good to go!

Please let me know if you have any further suggestions or any changes that need to be made.

Thanks!

2021-04-19 18:09 UTC, sethsimmons commented
Netlify preview looks good to me now that image tags are fixed.

Should be ready for review/merge!

2021-04-24 07:33 UTC, erciccione requested changes
Nice post. Two requests:

- Please run the png images through a png compressor like tinypng.com and then resubmit them. It will save a lot of space. For example `monero-hashrate-2021.png` could be shrinked from 330kB to 94kB, a ~72% saving.

- This article is taken from your blog, please add a disclaimer at the bottom of the post with a link to the original article (https://sethsimmons.me/posts/this-year-in-monero-2021/). It will avoid future confusions.

2021-04-24 07:33 UTC, erciccione commented on _posts/2021-04-18-this-year-in-monero.md
> +- Monero's main subreddit, [@monero](https://twitter.com/monero) gained ***69,209*** followers.
You meant "Twitter account"

2021-04-24 13:12 UTC, sethsimmons commented on _posts/2021-04-18-this-year-in-monero.md
> +- Monero's main subreddit, [@monero](https://twitter.com/monero) gained ***69,209*** followers.
Fixed.

2021-04-24 13:19 UTC, sethsimmons commented
> Nice post. Two requests:
> 
>     * Please run the png images through a png compressor like tinypng.com and then resubmit them. It will save a lot of space. For example `monero-hashrate-2021.png` could be shrinked from 330kB to 94kB, a ~72% saving.
> 
>     * This article is taken from your blog, please add a disclaimer at the bottom of the post with a link to the original article (https://sethsimmons.me/posts/this-year-in-monero-2021/). It will avoid future confusions.

All changes made and pushed. Will validate that they look alright once the CI runs and provides a preview.

Thanks for the suggestions!

2021-04-24 13:28 UTC, sethsimmons commented
For future reference https://github.com/kornelski/pngquant was a great tool for this, ended up using that for my own blog post as a test and was able to shrink them even further using:

`pngquant *.png --strip --skip-if-larger --quality=65-80 --verbose --ext=.png --force`

I'll use that in future posts.

2021-04-24 13:38 UTC, erciccione reviewed
> For future reference https://github.com/kornelski/pngquant was a great tool for this

Good to know. Thanks for the link :)

Just one more thing and then this will be good to go: could you update the file name with today's date? People using RSS feeds will be confused if they receive a feed for a post that appear to have been published a week ago. Nothing important, but since it's a quick fix, better do it.

2021-04-24 13:44 UTC, sethsimmons commented
> > For future reference https://github.com/kornelski/pngquant was a great tool for this
> 
> 
> 
> Good to know. Thanks for the link :)
> 
> 
> 
> Just one more thing and then this will be good to go: could you update the file name with today's date? People using RSS feeds will be confused if they receive a feed for a post that appear to have been published a week ago. Nothing important, but since it's a quick fix, better do it.

Done! Also added a minor note on the miner count numbers that I had added to my own blog in the meantime.

2021-04-24 13:50 UTC, erciccione approved these changes
Needs to be squashed.

2021-04-24 14:10 UTC, erciccione approved these changes

2021-04-24 20:02 UTC, merged