Add kryptocheck to merchants file
monero-project/monero-site pull request #1611
Opened 2021-05-07 06:07 UTC by phplernen

2021-05-07 07:16 UTC, erciccione requested changes
Please open an issue as requested: https://github.com/monero-project/monero-site/issues/new?assignees=&labels=%F0%9F%8F%AA+merchant%2C+%F0%9F%94%8D+Needs+investigation&template=new-merchant.md&title=Add+%3CNAME+OF+YOUR+BUSINESS%3E+to+the+list+of+merchants

2021-05-07 07:40 UTC, phplernen commented
> Please open an issue as requested: https://github.com/monero-project/monero-site/issues/new?assignees=&labels=%F0%9F%8F%AA+merchant%2C+%F0%9F%94%8D+Needs+investigation&template=new-merchant.md&title=Add+%3CNAME+OF+YOUR+BUSINESS%3E+to+the+list+of+merchants

@erciccione Okay, sry, did not know that.

2021-05-07 11:11 UTC, erciccione approved these changes

2021-05-08 06:28 UTC, phplernen commented
If this is fine now please let's get this merged.

2021-05-22 02:37 UTC, merged