Tools: add links to monero.fail node list and node map
monero-project/monero-site pull request #1731
Opened 2021-07-16 01:31 UTC by rating89us

2021-07-16 07:31 UTC, erciccione requested changes
I'm not sure if it makes sense to add two links to the same website but a different page. Better to add on single entry. Like:

Monero.fail (node list and map) - https://monero.fail/

2021-07-17 14:17 UTC, selsta commented
+1 for one link

2021-07-17 14:28 UTC, selsta approved these changes

2021-07-19 09:34 UTC, erciccione approved these changes

2021-07-27 20:44 UTC, merged