tools: add section 'payment gateways'
monero-project/monero-site pull request #1748
Opened 2021-07-30 08:08 UTC by erciccione

and transfer the content of the old section in the merchants page.
One service was removed (livingroomofsatoshi.com) because doesn't
look like they support Monero.

As mentioned in https://github.com/monero-project/monero-site/issues/1736#issuecomment-884103952

**Requires**  #1743

2021-07-30 18:23 UTC, selsta approved these changes

2021-08-07 22:36 UTC, rating89us requested changes

2021-08-07 22:36 UTC, rating89us commented on _i18n/en.yml
> +  gateaways: Payment Gateaways
```suggestion
  gateways: Payment Gateways
```

2021-08-07 22:36 UTC, rating89us commented on resources/tools/index.md
> +                        <h2>{% t tools.gateaways %}</h2>
```suggestion
                        <h2>{% t tools.gateways %}</h2>
```

2021-08-08 07:45 UTC, erciccione commented on _i18n/en.yml
> +  gateaways: Payment Gateaways
Fixed

2021-08-08 11:59 UTC, selsta approved these changes

2021-08-08 18:11 UTC, rating89us approved these changes

2021-08-08 18:12 UTC, rating89us commented on resources/tools/index.md
> +        <div class="left half col-lg-6 col-md-6 col-sm-12 col-xs-12">
```suggestion
        <div class="right half col-lg-6 col-md-6 col-sm-12 col-xs-12">
```

2021-08-08 18:15 UTC, rating89us requested changes

2021-08-08 18:15 UTC, rating89us commented on resources/tools/index.md
> +        <div class="left half col-lg-6 col-md-6 col-sm-12 col-xs-12">
```suggestion
        <div class="right half col-lg-6 col-md-6 col-sm-12 col-xs-12">
```

2021-08-08 18:17 UTC, rating89us requested changes

2021-08-08 18:17 UTC, rating89us commented on resources/tools/index.md
> +        <div class="left half col-lg-6 col-md-6 col-sm-12 col-xs-12">
```suggestion
        <div class="right half col-lg-6 col-md-6 col-sm-12 col-xs-12">
```

2021-09-21 03:02 UTC, QuickBASIC approved these changes

2021-09-29 01:28 UTC, merged