downloads: add feather wallet
monero-project/monero-site pull request #1757
Opened 2021-08-04 14:36 UTC by rating89us

Changes:
- add feather wallet to light wallets section
- fix "GitHub icon" aria-label of remaining wallets

2021-08-04 20:08 UTC, selsta approved these changes

2021-08-05 06:49 UTC, erciccione commented
@rating89us if we are waiting for Feather to go out of beta, please convert this PR to draft.

2021-10-29 19:24 UTC, selsta commented
ping @rating89us please put this out of draft mode

2021-10-31 11:27 UTC, erciccione requested changes
Why adding it in the middle instead of the end of the list? Not a big deal, just curious to know if there is a particular reason

2021-10-31 11:27 UTC, erciccione commented on downloads/index.md
> +                            <td><a class="ext-noicon" href="https://git.featherwallet.org/feather/feather" aria-label="GitHub icon"><span class="icon-github"></span></a></td>
Replace the github icon with the generic git icon:

```suggestion
                            <td><a class="ext-noicon" href="https://git.featherwallet.org/feather/feather" aria-label="GitHub icon"><span class="icon-git"></span></a></td>
```

2021-11-07 13:25 UTC, erciccione commented
Recovered with #1885 (added my change as well)

2021-11-07 13:25 UTC, closed without merging