blog: add v0.17.3.0 release notes
monero-project/monero-site pull request #1895
Opened 2021-12-03 23:46 UTC by selsta

2021-12-04 09:10 UTC, erciccione commented on _posts/2021-12-04-monero-0.17.3.0-released.md
> +This is the v0.17.3.0 point release of the Monero software. This release contains support for P2Pool.
```suggestion
This is the v0.17.3.0 point release of the Monero software. This release contains support for [P2Pool]({{ site.baseurl }}/2021/10/05/p2pool-released.html).
```

2021-12-04 12:52 UTC, selsta commented on _posts/2021-12-04-monero-0.17.3.0-released.md
> +This is the v0.17.3.0 point release of the Monero software. This release contains support for P2Pool.
done

2021-12-05 09:36 UTC, erciccione requested changes

2021-12-05 09:36 UTC, erciccione commented on _posts/2021-12-04-monero-GUI-0.17.3.0-released.md
> +[The latest CLI release notes can be found on the precedent blog post]({{ site.baseurl_root }}/2021/12/04/monero-0.17.2.0-released.html)
```suggestion
[The latest CLI release notes can be found on the precedent blog post]({{ site.baseurl_root }}/2021/12/04/monero-0.17.3.0-released.html)
```

2021-12-05 09:36 UTC, erciccione commented on _posts/2021-12-04-monero-GUI-0.17.3.0-released.md
> +- weblate
This should be removed.

2021-12-05 19:39 UTC, selsta commented on _posts/2021-12-04-monero-GUI-0.17.3.0-released.md
> +[The latest CLI release notes can be found on the precedent blog post]({{ site.baseurl_root }}/2021/12/04/monero-0.17.2.0-released.html)
done

2021-12-05 20:22 UTC, erciccione approved these changes

2021-12-07 11:13 UTC, binaryFate commented
Hashes are ok

2021-12-07 11:13 UTC, merged