Adding a swapper
monero-project/monero-site pull request #1910
Opened 2021-12-30 12:48 UTC by jerzybrzoska

XMR does not always show up as an option (most likely due to blocking some countries, this can be overcome with VPN or selecting the appropriate tor exit node). Nevertheless, **fixedfloat.com** seems to be the only swapper that offers BTC lightning to Monero.

2021-12-30 16:47 UTC, selsta reviewed
Are you affiliated with this website? We usually don't add any new swapper websites unless they have a good reputation in the community and exist for a while. I'll try to get some feedback about them.

2021-12-31 18:12 UTC, jerzybrzoska commented
No, I'm not. 

> Are you affiliated with this website? 

I'm a BTC-lightning user, and so I came across it in 2020 here: <https://lightningnetworkstores.com/?digital_goods=all&sort=best&search&safemode=false&tags=exchange>

2022-01-01 11:28 UTC, erciccione requested changes
NACK for me

2022-01-04 16:01 UTC, selsta reviewed
Could you please force push and add them to the bottom of the list?

2022-02-27 18:32 UTC, Ianigroea commented
Must say I am strongly against because they are holding my 6000 USD a hostage and play smart about it.

https://www.reddit.com/r/Monero/comments/t1gyoo/fixedfloat_scammed_me_for_6000_usd/

And they are marked as not trusted by Feather wallet developer.

https://xmrguide.org/exchanges

They are just taking the funds, not even doing KYC or making a refund and refuse a service like some exchanges do.

This is not a monero-friendly exchange, this is selective scam and incompetence.

2022-02-27 18:39 UTC, selsta commented
FWIW they replied here: https://reddit.com/r/Monero/comments/t1gyoo/_/hygp7bc/

2022-02-28 00:16 UTC, Ianigroea commented
Since the post got removed by r/Monero moderators I will leave this so you can judge yourself before making a decision

https://i.imgur.com/xAV2xUX.png

https://i.imgur.com/7iUjKYa.png

https://i.imgur.com/j0SVQfP.png

Exchange should be a professional business, not a liar and selective scammer.

2022-02-28 00:27 UTC, selsta commented
Freezing funds in case of LE getting involved is nothing unusual for centralized exchanges. They have asked you for proof that the source of the funds is Bisq and as far as I can tell you haven't replied yet.

2022-02-28 00:36 UTC, Ianigroea commented
This kind of practice is not seen yet with any other exchange that exist, because I would be able to sue them and get my money back.

Which LE getting involved? Did you saw any proof of that ? Was there any proof provided BTC was tainted?

I clearly mentioned I am ready to provide both KYC and contact trough my lawyer which they both ignored and continue with their ignorance which is not something Monero site should support.

Just my opinion.

I will be back in month or two and three and four to see where that Law enforcement request and criminal investigation came to.

2022-02-28 00:39 UTC, Ianigroea commented
They promised showing proof to both /r/Monero moderators and BestChange (crypto aggregator) request from law enforcement for seizure of my funds and to this day, that has not happened.

2022-02-28 00:41 UTC, selsta commented
> which is not something Monero site should support

It's not added yet, but like I said all centralized exchanges will use some form of blockchain analysis and freeze your funds if they get marked as stolen / hacked.

> I clearly mentioned I am ready to provide both KYC

They didn't ask you for KYC, they just wanted screenshots / or another proof that your funds came from Bisq. That should be quite easy and quick to get.

2022-03-09 22:02 UTC, selsta commented
I have been in contact with FixedFloat.

They provided proof that the funds were marked as stolen and then later sent to FixedFloat. @Ianigroea claimed that they were sent from Bisq but didn't provide any evidence so far. No KYC was requested in this case. In my opinion, asking for a proof for the source of funds is reasonable and not privacy invasive.

I'm still in favor of adding them to the website.

2022-03-12 15:45 UTC, Ianigroea commented
I hope you are not affiliated with these scammers.

You obviously failed to comprehend few things but please care to explain further.

1) Proof you saw was it obtained from reputable AML/KYT software like chainanalysis/ciphertrace or was it some non-licensed, custom and speculative software like amlbot.com ?

2) Under which law they have authority to host custody of my coins and until when? Did they provided you proof of any law enforcement contact?

I say that they shouldn't be added until this case resolved, because I got in touch with other people that are ready to testify here and in front of court that FixedFloat is holding more then 500 000 in USD value from BTC -> XMR transactions.

They are holding half a million of monero community money until when? Until we all forget this happened and they can spend their coins on fancy boat?

I will be here for next 6 months waiting to hear new bullshit story of these clever scammer group.

2023-08-17 15:37 UTC, merged