verify source integrity in workflows
monero-project/monero-site pull request #1971
Opened 2022-05-26 22:03 UTC by plowsof

aims to close #1576

2022-05-27 08:49 UTC, erciccione requested changes
Please improve the commit message to something clearer. Like `workflows: add source integrity validation to hashes.yml`.

2022-05-27 11:43 UTC, plowsof commented
Thanks for that, i've changed the commit message, and removed some extra white spaces i was using to compare the git clone lines.  Please bare with me on these git nuances, i created a patch on my master branch just yesterday, oops!

2022-05-29 19:43 UTC, selsta approved these changes

2022-06-17 06:31 UTC, erciccione approved these changes

2022-06-30 19:04 UTC, merged