Change "magazines" section to "newsletters" and update resources at library page
monero-project/monero-site pull request #2044
Opened 2022-09-12 16:22 UTC by HardenedSteel

I renamed "magazines" title because using "newsletters" title is more appropriate. I didn't write a description for resources, if needed feel free to make suggestion.  closes #1976

2022-09-12 20:45 UTC, plowsof commented
If the [moneromoons ccs proposal](https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/336) is not merged to funding , he will not produce the newsletter anymore , something to consider (and is currently away for the next 4 weeks)

2023-01-03 11:51 UTC, erciccione requested changes
Better add a brief description of each newsletter otherwise it's quite ugly and differs from the style of the rest of the page.

2023-03-03 08:45 UTC, erciccione commented
Opinions about my comment above?

2023-03-13 09:52 UTC, erciccione commented
@HardenedSteel i don't know as i'm not very familiar with any of them, but even just author and structure (published every N) would be enough.

2023-04-27 12:55 UTC, HardenedSteel commented on _i18n/en.yml
> +  moneropedia:
Thank you!

2023-05-07 07:48 UTC, erciccione requested changes

2023-05-07 07:48 UTC, erciccione commented on library/index.md
> +                <h3><a href="https://localmonero.co/the-monero-standard">The Monero Standard Series</a></h3>
Here we should either make `series` translatable, or remove it all together and leave only `The Monero Standard`

2023-05-07 07:48 UTC, erciccione commented on library/index.md
> +                <h3><a href="https://monero.observer/tag/blitz/">Monero Observer Blitz Series</a></h3>
Same as above: should be `Monero Observer Blitz`, or `series` should be translatable.

2023-05-18 12:14 UTC, erciccione commented
ping @HardenedSteel

2023-05-19 13:32 UTC, erciccione approved these changes

2023-05-25 22:35 UTC, plowsof commented
we can merge as is OR add/test html scripting with this pull request ive made here https://github.com/HardenedSteel/monero-site/pull/2

2023-05-26 10:59 UTC, erciccione commented
I'd merge as it is, since this is already reviewed and i would open a dedicated pr after if you want to propose that patch. That said, personally i don't see the need to increase complexity and add a new file. It's only two entries, but even if it was more, the current structure could still be used without problems.

2023-06-06 18:49 UTC, merged