maintenance of merchants.yml
monero-project/monero-site pull request #2129
Opened 2023-02-18 01:41 UTC by HardenedSteel

1. Removed these because of delist:
* https://www.bitci.com
* https://bitni.com
* https://www.coinswitch.co
* https://exmo.com/
* https://www.kaiserex.com/

2. Removed these because of no longer operating:
* https://rexi.cc - Site is offline
* https://www.morphtoken.com
* https://www.tuxexchange.com - Irrelevant site.

3. Changed Fixedfloat's link to BTC/XMR pair page.
4. Changed Bitfinex's link to XMR/BTC pair page.
5. Fixed up broken Binance link - closes #2040 
6. Removed Localmonero because Agoradesk is the same site with additional BTC support.

2023-02-20 14:33 UTC, plowsof commented
is this file currently in use somewhere? is there somewhere with the entire list on site? (removing localmonero will raise some eyebrows)

2023-02-21 04:16 UTC, HardenedSteel commented
@plowsof 
> is this file currently in use somewhere? is there somewhere with the entire list on site?

I searched up but couldn't find anything. If not needed we may delete it.
> removing localmonero will raise some eyebrows

As I said, Agoradesk and Localmonero are basically the same site, Agoradesk additionally has BTC support. Maybe keeping only Localmonero and not Agoradesk can be better, but I don't see any reason to keep both sites.

2023-02-24 12:23 UTC, erciccione requested changes
please squash

2023-03-03 08:46 UTC, erciccione approved these changes

2023-03-14 14:34 UTC, merged