Update index.md
monero-project/monero-site pull request #2183
Opened 2023-07-06 15:41 UTC by MajesticBank

Seems SideShift dropped support for XMR, according to their website and also https://kycnot.me/changelog

[Sideshift.ai](https://kycnot.me/exchange/sideshift.ai) no longer operates with XMR.

Thinking it would be useful to more options available for users to explore.

I would maybe put swappers in this order (if you find order relevant)

ChangeNow
MajesticBank
SimpleSwap
Godex

2023-07-06 15:43 UTC, MajesticBank commented
Support over live chat wrote me this:

Me:

Hello
Will support for Monero coin be back or it's forever ?


Support:

SideShift.ai - HELP typically replies in a few hours.
Roy_Reynolds profile
There is currently no plans to bring back in the near future
Roy_Reynolds profile
Could still be listed again in the future. Anything is possible


Me:
Thanks for the info
1m ago. Seen

2023-07-07 12:18 UTC, erciccione reviewed
While removing sideshift is necessary after the delisting, adding MajesticBank to this page should be discussed and approved by the community first. Please also edit the title of the pull request to make clear that you are not only removing sideshift, but also suggesting to replace it with majesticbank

2023-07-07 16:40 UTC, SamsungGalaxyPlayer requested changes
NACK

2023-07-08 09:50 UTC, erciccione commented
@SamsungGalaxyPlayer could you elaborate on your NACK?

2024-01-21 16:37 UTC, nahuhh commented
Close in favor of #2184

@MajesticBank - open a pr for just majestic

2024-02-25 13:58 UTC, plowsof commented
i think it would be easier to close this. then open another PR to add MajesticBank to merchants for people to discuss. (as per the above comment). more context in this comment/issue: https://github.com/monero-project/monero-site/issues/2247#issuecomment-1962941440

2024-05-08 17:05 UTC, closed without merging