Rm paragraph about locked outputs being used as decoys
monero-project/monero-site pull request #2198
Opened 2023-10-14 23:51 UTC by jeffro256

Locked outputs cannot be used as ring members since the protocol (by design) has no way of knowing which output is the "true" spend inside of a ring signature. Thus, the protocol only validates ring signatures where each member of the ring is properly unlocked.

2023-10-16 13:49 UTC, erciccione requested changes
Only the original file in english should be edited (`_i18n/en/resources/moneropedia/unlocktime.md`)

2023-10-19 00:32 UTC, jeffro256 commented
Should I modify the commit now?

2023-10-19 09:54 UTC, erciccione approved these changes
Would be better to improve the commit description to specify what is being changed, but it's good to go.

2023-10-19 16:49 UTC, jeffro256 commented
Is this commit message better?

2023-10-20 08:31 UTC, erciccione approved these changes
That's perfect, thanks.

2023-10-26 01:26 UTC, merged