newsletters: add revuo monero
monero-project/monero-site pull request #2217
Opened 2024-01-10 13:29 UTC by rottenwheel

Considering Revuo Monero was initially started by Diego 'rehrar' Salazar in 2019, has been, historically speaking the one newsletter under the Core Workgroup umbrella while he was their liason, more than 100 issues were shared via the 'official' Twitter profile, @monero, archive is found on LocalMonero's website and overall its good standing of audience and content, I think it is appropriate for Revuo Monero to be named and linked as well, keeping things cohesive.

2024-01-10 14:23 UTC, erciccione commented
> more than 100 issues were shared via the 'official' Twitter profile, https://github.com/monero

The Monero twitter profile has stopped sharing the Revuo written by @rottenwheel in May 2022, after it was pointed out that the author was currently banned from most Monero channels for behaviour such harassment, doxxing of contributors, toxic behaviour and much more.

That's why the Revuo was already rejected in #2044. Reiterated toxic behaviour can be seen in https://github.com/monero-project/monero-site/issues/1976#issuecomment-1884436228.

2024-01-10 15:40 UTC, SamsungGalaxyPlayer approved these changes

2024-01-11 08:53 UTC, plowsof commented
please squash and consider setting a trend for future newsletter pr commit titles "newsletters: add revuo monero". i like how you added your newsletter to the top of the list, this is the confidence we like to see. 

looking through https://revuo-xmr.com/, i see none of the aforementioned behaviour on display. I see a Monero newsletter running on FOSS, with, to-the-point / no fluff informative publications. I have no problem with someone stumbling upon this newsletter after browsing the library page, and welcome more.

moving forward, the last issue was in November, and i am aware of a vote(s) circulating to decide if Revuo should continue. can @rottenwheel speak about the feedback received so far? and if Revuo is going to continue?

2024-01-13 04:17 UTC, HardenedSteel commented
> > more than 100 issues were shared via the 'official' Twitter profile, https://github.com/monero
> 
> The Monero twitter profile has stopped sharing the Revuo written by @rottenwheel in May 2022, after it was pointed out that the author was currently banned from most Monero channels for behaviour such harassment, doxxing of contributors, toxic behaviour and much more.
> 
> That's why the Revuo was already rejected in #2044. Reiterated toxic behaviour can be seen in [#1976 (comment)](https://github.com/monero-project/monero-site/issues/1976#issuecomment-1884436228).

I couldn't find toxic behavior from @rottenwheel in your comment or your other claims, also he refuses your claims. 

Also let's keep past in past. We don't need drama.

2024-01-17 01:01 UTC, HardenedSteel requested changes
I think its better to squash changes.

2024-01-17 01:16 UTC, nahuhh requested changes
Revert commits - he latest messed up.

also not sure why the paperwallet generator commits were pulled in - this pr really shouldnt touch them.. (if there are ever any conflicts, rebase and force push instead)

i _would_ say squash, but commits need to be reverted anyway, so i say just redo it and then push all changes in 1 commit (instead of 2). 

@plowsof

2024-01-17 09:37 UTC, plowsof commented
Just git things (still struggling myself)  https://github.com/plowsof/monero-site/tree/newsletters_revuo

2024-01-17 18:53 UTC, rbrunner7 approved these changes
Technically the changes look ok, the PR correctly makes the changes that it claims to do.

As to the claims that the current author of the newletter has a history of conflicts and bans in the Monero community: Well, what do I know. Similarly to @plowsof , I look at this now from the point of view of the readers of the website, and seems to me those are not affected by whatever happened in the past of the author, but they get to read a solid newsletter. Which I can approve.

2024-01-17 19:08 UTC, plowsof approved these changes

2024-01-18 02:23 UTC, HardenedSteel approved these changes

2024-02-06 21:12 UTC, merged