downloads: fix stack wallet
monero-project/monero-site pull request #2365
Opened 2024-08-31 19:30 UTC by nahuhh

2024-09-01 18:41 UTC, plowsof approved these changes

2024-09-01 22:09 UTC, HardenedSteel requested changes
Can you add a comment to your commit about what you did? Like you fixed the mobile view. It confused me at first what line 299 is about

2024-09-02 12:08 UTC, nahuhh commented
> Can you add a comment to your commit about what you did? Like you fixed the mobile view. It confused me at first what line 299 is about

done

2024-09-02 13:47 UTC, HardenedSteel approved these changes

2024-09-02 14:23 UTC, merged