merchants: delist kraken for europe
monero-project/monero-site pull request #2382
Opened 2024-10-10 15:12 UTC by nahuhh

2024-10-10 17:08 UTC, plowsof commented
if kraken still have Euros (but no direct xmr/eur) we can still have EUR, just without the *

2024-10-10 17:43 UTC, nahuhh commented
> if kraken still have Euros (but no direct xmr/eur) we can still have EUR, just without the * 

They will have eur to ltc, but no xmr at all..

2024-10-10 18:20 UTC, plowsof commented
ok then EUR can stay without * (the asterisk just says that they have a direct fiat/xmr pairing. e.g. there is no £GBP/xmr but they have gbp :+1:

2024-10-10 21:00 UTC, plowsof approved these changes

2024-10-11 02:07 UTC, HardenedSteel requested changes

2024-10-11 02:07 UTC, HardenedSteel commented on community/merchants/index.md
> +            <li><a href="https://www.kraken.com/">Kraken</a> (USD*, CAD, JPY, AUD, CHF)</li>
```suggestion
            <li><a href="https://www.kraken.com/">Kraken</a>** (EUR*, USD*, CAD, JPY, AUD, CHF)</li>
```

Then add;
** Unavailable for EEA clients.

2024-10-11 05:51 UTC, HardenedSteel approved these changes

2024-10-11 09:20 UTC, nahuhh commented
Added note for EEA

2024-10-31 22:32 UTC, merged