zh-cn translation of 66 Moneropedia entries
monero-project/monero-site pull request #937
Opened 2020-04-17 10:23 UTC by erciccione

Originally opened on Gitlab: https://repo.getmonero.org/monero-project/monero-site/-/merge_requests/1121

This PR has been opened for months. It contains the translation of 66 moneropedia entries. Until now, nobody volunteered for the tasks. Understandable, since it's a huge amount of work to review, but we cannot merge it until somebody review at least part of it.

I will take care of rebasing it and make it ready to merge (was committed 7 months ago and never rebased), but we need a reviewer.

2020-05-13 18:21 UTC, mofadashi commented
I would like to review it, but where I can find the original documentary?

2020-05-13 18:48 UTC, erciccione commented
That would be great :) the original files are here: https://github.com/monero-project/monero-site/tree/master/_i18n/en/resources/moneropedia

Consider that some of the english files have been updated in the meantime, so the content could be slightly different. Would be ideal to have the missing parts translated as well.
Feel free to reach out if you need help.

2020-05-14 22:01 UTC, mofadashi commented on _i18n/zh-cn/resources/moneropedia/account.md
> +最后，在点击电子邮件或不知名、不可信网站的链接时要格外小心，因为安装在你电脑上的恶意软件可能会在你调用资金之前，等着你进入你的门罗币账户。
“因为安装在你电脑上的恶意软件可能会在你调用资金之前，等着你进入你的门罗币账户。” -->因为安装在你电脑上的恶意软件会对你的账户虎视眈眈，在你进入账户后拿走你的钱

2020-05-15 07:41 UTC, erciccione commented
@mofadashi I don't speak chinese, so i cannot really understand the context of your review. Could you use [GitHub suggestions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request) when suggesting changes, so that i can jsut apply that.

Also, you don't need to review [the files listed here](https://github.com/monero-project/monero-site/issues/910#issuecomment-628562953), i will remove them soon from the repository and this PR.

2020-05-19 23:32 UTC, mofadashi requested changes
Made some changes during the review

2020-05-19 23:51 UTC, mofadashi commented on _i18n/zh-cn/resources/moneropedia/account.md
> +您的帐户包含您发送和接收的所有门罗币@交易。你的账户余额是你收到的所有门罗币的总和，减去你发送的门罗币。当使用门罗币时，您可能会注意到您的帐户有两个余额，一个锁定的和一个非锁定的余额。未锁定余额包含可以立即使用的资金，而锁定余额包含不能立即使用的资金。您可能收到一个设置了@解锁时间的交易，或者您可能发送了一些门罗币并等待@找零回到您的钱包，这两种情况都可能导致这些资金被锁定一段时间。
```suggestion
您的帐户包含您发送和接收的所有门罗币@交易。你的账户余额是你收到的所有门罗币减去你发送的门罗币。当使用门罗币时，您可能会注意到您的帐户有两个余额，一个锁定的和一个未锁定的余额。未锁定余额包含可以立即使用的资金，而锁定余额包含不能立即使用的资金。您可能收到一个设置了@解锁时间的交易，或者您可能发送了一些门罗币并等待@找零回到您的钱包，这两种情况都可能导致这些资金被锁定一段时间。
```

2020-05-19 23:51 UTC, mofadashi commented on _i18n/zh-cn/resources/moneropedia/account.md
> +为了保护您的帐户隐私，您必须保护这两个密钥。另一方面，公钥显然是公开的(它们是门罗币帐户地址的一部分)。对于普通的公/私钥加密，有人可以通过使用您的任何一个公钥加密来发送一条私钥消息，然后您将是惟一能够使用您的私钥解密它的人。
```suggestion
为了保护您的帐户隐私，您必须保护这两个密钥。另一方面，公钥显然是公开的(它们是门罗币帐户地址的一部分)。对于普通的公/私钥加密，有人可以通过使用您的任何一个公钥加密来发送一条私钥消息，而您将是惟一能够使用您的私钥解密它的人。
```

2020-05-19 23:53 UTC, mofadashi commented on _i18n/zh-cn/resources/moneropedia/account.md
> +当您使用私有的@支付密钥管理您自己的门罗币帐户时，您将全权负责您资金的安全性。谢天谢地，门罗币让您的帐户备份变得非常容易。当您第一次创建一个门罗币帐号时，您的帐号会有一个独一无二的@助记种子，由你选择的语言的13或25个单词组成。**该种子是您唯一需要为您的帐号备份的东西**，因此必须将其记录下来并安全地存储。永远不要把种子储存在别人可以看到的地方!
```suggestion
当您使用私有的@支付密钥管理您自己的门罗币帐户时，您将全权负责您资金的安全性。谢天谢地，门罗币让您的帐户备份变得非常容易。当您第一次创建一个门罗币帐号时，您的帐号会有一个独一无二的@助记种子，由你选择的语言的13或25个单词组成。**该种子是您帐号备份唯一需要东西**，因此必须将其记录下来并安全地存储。永远不要把种子储存在别人可以看到的地方!
```

2020-05-23 15:46 UTC, mofadashi commented
> @mofadashi I don't speak chinese, so i cannot really understand the context of your review. Could you use GitHub suggestions when suggesting changes, so that i can jsut apply that.
> Also, you don't need to review the files listed here, i will remove them soon from the repository and this PR.

I finished my suggestion. could you take a look at it? Merge it?

2020-05-23 17:18 UTC, erciccione commented
@mofadashi SInce this is not urgent i'm giving other translators time to review your suggestions. If nobody shows up i'll just add them.

2020-06-05 12:13 UTC, erciccione commented
Added @mofadashi's review, fixed some minor technical issues and rebased

2020-07-31 20:07 UTC, merged